version: "3.4"
services:
  db:
    build: ./mysql/
    container_name: db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/log/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping --host=127.0.0.1 --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --port=3306"]
    ports:
      - "3306:3306"
  rails:
    build: ./api/server/
    container_name: wt4u_api_rails
    command: ["./run.sh"]
    container_name: rails
    env_file:
      - ./api/server/.env
    volumes:
      - ./api/server/:/code/
      - public:/code/public/
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
  api-nginx:
    build: ./api/nginx/
    container_name: wt4u_api_nginx
    volumes:
      - public:/code/public/
    ports:
      - "8080:80"
    depends_on:
      rails:
        condition: service_healthy
  react:
    build: ./frontend/
    container_name: react
    volumes:
      - ./frontend/front/:/code/
    ports:
      - "8000:8000"
    command: ["/run.sh"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
  front-nginx:
    build: ./frontend/nginx/
    container_name: front_nginx
    ports:
      - "80:80"
    depends_on:
      react:
        condition: service_healthy
volumes:
  db-data:
  public:
